services:
  app.command.organizacja.dodaj:
    class: AppBundle\CommandBus\Organizacja\DodajOrganizacjeCommand
    arguments: [@security.token_storage]

  app.handler.organizacja.dodaj:
    class: AppBundle\CommandBus\Organizacja\DodajOrganizacjeCommandHandler
    arguments: [@app.repository.organizacja]
    tags: [{ name: command_handler, handles: AppBundle\CommandBus\Organizacja\DodajOrganizacjeCommand }]