services:
  # organizacja
  app.command.organizacja.dodaj:
    class: AppBundle\CommandBus\Organizacja\DodajOrganizacjeCommand
    arguments: [@security.token_storage]
  app.handler.organizacja.dodaj:
    class: AppBundle\CommandBus\Organizacja\DodajOrganizacjeCommandHandler
    arguments: [@app.repository.organizacja]
    tags: [{ name: command_handler, handles: AppBundle\CommandBus\Organizacja\DodajOrganizacjeCommand }]

  app.command.organizacja.edytuj:
    class: AppBundle\CommandBus\Organizacja\EdytujOrganizacjeCommand
    arguments: [@security.token_storage]
  app.handler.organizacja.edytuj:
    class: AppBundle\CommandBus\Organizacja\EdytujOrganizacjeCommandHandler
    arguments: [@app.repository.organizacja]
    tags: [{ name: command_handler, handles: AppBundle\CommandBus\Organizacja\EdytujOrganizacjeCommand }]

  # pracownik
  app.command.pracownik.dodaj:
    class: AppBundle\CommandBus\Pracownik\DodajPracownikaCommand
    arguments: [@security.token_storage]