services:
  app.controller.dashboard:
    class: AppBundle\Controller\DashboardController
  app.controller.organizacja:
    class: AppBundle\Controller\OrganizacjaController
    arguments: [@app.command.organizacja.dodaj, @simple_bus.command_bus, @app.repository.organizacja]
    calls:
      - [setContainer, [@service_container]]
      - [setUnitOfWork, [@unit_of_work]]
  app.controller.pracownik:
    class: AppBundle\Controller\PracownikController
    arguments: [@app.command.pracownik.dodaj, @simple_bus.command_bus, @app.repository.pracownik]
    calls:
      - [setContainer, [@service_container]]
      - [setUnitOfWork, [@unit_of_work]]