services:
  app.doctrine.data_entity_listener:
    class: AppBundle\Doctrine\DataEntityListener
    tags:
      - { name: doctrine.event_listener, event: prePersist }
      - { name: doctrine.event_listener, event: preUpdate }