services:
  app.doctrine.data_entity_listener:
    class: AppBundle\Doctrine\DataEntityListener
    tags:
      - { name: doctrine.event_listener, event: prePersist }
      - { name: doctrine.event_listener, event: preUpdate }

  app.command.organizacja.dodaj:
    class: AppBundle\CommandBus\Organizacja\DodajOrganizacjeCommand
    arguments: [@security.token_storage]

  app.controller.dashboard:
    class: AppBundle\Controller\DashboardController
  app.controller.organizacja:
    class: AppBundle\Controller\OrganizacjaController
    arguments: [@app.command.organizacja.dodaj]