services:
  app.doctrine.data_entity_listener:
    class: AppBundle\Doctrine\DataEntityListener
    tags:
      - { name: doctrine.event_listener, event: prePersist }
      - { name: doctrine.event_listener, event: preUpdate }

  app.listener.ajax_response:
    class: AppBundle\EventListener\AjaxResponseListener
    arguments: [@monolog.logger.ajax, %kernel.debug%]
    tags: [{ name: kernel.event_subscriber}]

  app.repository.organizacja:
    class: AppBundle\Repository\Doctrine\OrganizacjaRepository
    arguments: [@doctrine.orm.entity_manager]

  app.command.organizacja.dodaj:
    class: AppBundle\CommandBus\Organizacja\DodajOrganizacjeCommand
    arguments: [@security.token_storage]

  app.handler.organizacja.dodaj:
    class: AppBundle\CommandBus\Organizacja\DodajOrganizacjeCommandHandler
    arguments: [@app.repository.organizacja]
    tags: [{ name: command_handler, handles: AppBundle\CommandBus\Organizacja\DodajOrganizacjeCommand }]

  app.form.type.organizacja:
    class: AppBundle\Form\Type\OrganizacjaType
    tags: [{ name: form.type, alias: organizacja }]

  app.controller.dashboard:
    class: AppBundle\Controller\DashboardController
  app.controller.organizacja:
    class: AppBundle\Controller\OrganizacjaController
    arguments: [@app.command.organizacja.dodaj, @simple_bus.command_bus, @app.repository.organizacja]
    calls:
      - [setContainer, [@service_container]]
      - [setUnitOfWork, [@unit_of_work]]
